version: "3.8"

services:
  snap-shot-api:
    build:
      context: ./snap-shot-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./snap-shot-testing-fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ../postrgress/pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge
