version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile

    ports:
      - "3307:3307"
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      BASE_URL: 127.0.0.1
      PORT: 3307
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - api
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ../postrgress/pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    internal: true
